### PR TITLE
Updated stix mappings with new MBC v2.3 syntax

### PR DESCRIPTION
**Pull request by ryantxu1**

### CODE REVIEW

**Comment by ryantxu1** [comment]
This is replacing the previous stix representation for MBC v2.3. 

Due to the formatting changes to the mbc-markdown pages, the stix generation process needed to be updated extensively. This fixes a lot of incorrect sub-behavior names and relationship-matching in the previous version

**Comment by ryantxu1** [comment]
Example: 

This is an OLD stix mapping: 
```
        {
            "type": "attack-pattern",
            "spec_version": "2.1",
            "id": "attack-pattern--4ce382af-356c-4906-b6f1-e44b4d71ed02",
            "created_by_ref": "identity--b73c59c1-8560-449a-b8d0-c2ce0533c5bf",
          "created": "2021-02-10T06:49:31.988483Z",
          "modified": "2022-09-08T18:26:13.383868Z",
          "name": "AES::Decrypt Data",
          "description": "Malware decrypts data encrypted with the AES algorithm.",
          "kill_chain_phases": [
              {
                  "kill_chain_name": "mitre-mbc",
                  "phase_name": "cryptography-micro-objective"
              }
          ],
          "object_marking_refs": [
              "marking-definition--093b6375-cd45-4aa3-8f91-6a03ddd7a3d3"
          ],
          "external_references": [
              {
                  "source_name": "mitre-mbc",
                  "url": "https://github.com/MBCProject/mbc-markdown/blob/v2.3/micro-behaviors/cryptography/decrypt-data.md",
                  "external_id": "C0031.001"
              }
          ],
          "x_mitre_is_subtechnique": true
      }, 

```

The name "AES::Decrypt Data" is incorrect and is now changed to just "AES"

**Comment by watgh** [comment]
Shouldn't the same IDs be used, but just the  content be updated with a new modification date?

**Comment by dzbeck** [comment]
Thanks, @watgh - very good point. We hope to generate and tag such a version soon...

**Pull request merged**
